version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      graphql:
        patterns:
          - '@apollo/*'
          - 'graphql*'
          - '@as-integrations/*'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/*'
      linting:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
